export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/dashboard',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  USERS: '/users',
  CATEGORIES: '/categories',
  BRANDS: '/brands',
  PRODUCTS: '/products',
  REVIEWS: '/reviews',
  BANNERS: '/banners',
  BLOGS: '/blogs',
  FAQS: '/faqs',
  FAQ_CATEGORIES: '/faq-categories',
  SIZES: '/sizes',
  COLORS: '/colors',
  NEWSLETTER: '/newsletter',
  CONTACT: '/contact',
  COUPONS: '/coupons',
  POLICIES: '/policies',
  CARTS: '/carts',
  WISHLISTS: '/wishlists',
  ABOUT: '/about',
  IG_POSTS: '/ig-posts',
  SETTINGS: '/settings',
  SALE_BANNER: '/sale-banner',
  PROFILE: '/profile',
};
